# Generated by Django 3.1.7 on 2022-01-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_post_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alternativeIcon',
            field=models.ImageField(null=True, upload_to='alternativeIcons/'),
        ),
    ]
